name: Alliance Legal Video
favicon: null
layout_spectrum: 0.455100558931008
typography_spectrum: 0.5807528279256076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.038906440837308764
  lightness: 0.43038823385722935
  saturation: 0.656550508690998
  rhythmicContrast: 0.5330977290868759
purpose: []
